### ISSUE TITLE
After I do the setup and launch it, nothing happens

### ISSUE THREAD

**Issue by BaltimoreGamingYT** [FluxpointDev/MultiRPC#12]
So basically just nothing happens, it shows up in task manager for like half a second, then just disappears.

**Comment by xXBuilderBXx** [comment]
Do you have a different anti-virus like avast that might have blocked the installer and try reinstall.

**Comment by xXBuilderBXx** [comment]
@BaltimoreGamingYT hello did you solve the issue?
