### ISSUE TITLE
External API support?

### ISSUE THREAD

**Issue by Davilarek** [FluxpointDev/MultiRPC#13]
Is it possible to get some basic functions from this cool app using external application?

**Comment by Azyyyyyy** [comment]
If you just want to have a way to create a rich presence then it will be best to use the [library](https://github.com/Lachee/discord-rpc-csharp) that we use for talking to discord. 

If this isn't the case then in the [rewrite](https://github.com/FluxpointDev/MultiRPC/tree/rewrite) that is being worked on they will be the groundwork for custom pages to be possible which might be something to look out for 👍

**Comment by Davilarek** [comment]
I see, thanks mate, Discord RPC lib is what I'm looking for.
