### ISSUE TITLE
[Beta] MultiRPC just suspends when launched.

### ISSUE THREAD

**Issue by PhoenixAceVFX** [FluxpointDev/MultiRPC#23]
So I've gone ahead and done some troubleshooting but I can't figure out whats going on.
It was working fine a few minutes ago and now this suddenly started happening.
If I try to resume it (or let it resume on its own given it ever does) I get this error.
![image](https://user-images.githubusercontent.com/38572203/140598785-01884e15-7108-45ce-8f73-dd888bbd1add.png)

**Comment by xXBuilderBXx** [comment]
Thanks for reporting the issue can you tell me what windows version you are running and the version/name of the build you downloaded from https://github.com/FluxpointDev/MultiRPC/releases

**Comment by PhoenixAceVFX** [comment]
I'm on Windows 11 (not sure how to check the exact version of windows 11, i know im on the latest update)
and I downloaded 7V Custom Profiles

**Comment by PhoenixAceVFX** [comment]
ooooh something on my pc was preventing it from accessing the Docuements/MultiRPC-Beta location
i fixed that and now it works
