### ISSUE TITLE
[Beta] Linux - pop os blocking multirpc from checking processes?

### ISSUE THREAD

**Issue by xXBuilderBXx** [FluxpointDev/MultiRPC#24]
![image](https://user-images.githubusercontent.com/17956143/145503856-4937480c-473a-4739-b26a-65f03238aa12.png)

User is running Pop OS and is able to start rpc but something is blocking the app from checking/finding the Discord process.

**Comment by Azyyyyyy** [comment]
As said in the discord server, that's seeing that Discord is open but still thinks that it's not fully open, likely that our check needs changing for other OS's that aren't Windows. Will do some debugging for Linux later today

**Comment by Azyyyyyy** [comment]
This has been fixed and will be in the next release coming shorty
