### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by lucsoft** [FluxpointDev/MultiRPC#5]

**Comment by xXBuilderBXx** [comment]
This is planned and one of the devs that helps me Azy is working hard to add support, thanks for using the app and i will keep this open for now.

**Comment by xXBuilderBXx** [comment]
Hi thanks for using MultiRPC we now have support for it using Discord games, this will allow us to add multiplatform support and better updating.
You can request a gift code from me Builderb#0001 or join the support server https://discord.gg/TjF6QDC

**Comment by AzyIsCool** [comment]
Progress on a cross-platform version will be in the [rewrite](https://github.com/FluxpointDev/MultiRPC/tree/rewrite) branch, when it is stable enough to be used We'll tag you in this issue 🐱‍💻
