### ISSUE TITLE
Admin Mode??

### ISSUE THREAD

**Issue by ErikPDev** [FluxpointDev/MultiRPC#7]
Whenever I click the "admin mode" button it just closes MultiRPC.

**Comment by xXBuilderBXx** [comment]
It should launch MultiRPC in admin mode with the windows prompt but i will check to see if there is any issues.

**Comment by xXBuilderBXx** [comment]
Does the account you are signed into have admin or is there a program on your computer that might be blocking this?

**Comment by ErikPDev** [comment]
I blocked Windows Defender permanently because it keeps blocking some apps I own( ͡° ͜ʖ ͡°), and my windows account has admin perms.

**Comment by ErikPDev** [comment]
And now there is an api issue on all ids. lol

**Comment by xXBuilderBXx** [comment]
@ErikPDev fixed the api issue with ids, discord changed something and broke it.

**Comment by ErikPDev** [comment]
Alright, Thanks mate!
